apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docupilot-api
  namespace: docupilot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: docupilot.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docupilot-api
                port: {number: 80}
